---

- name: Manage backups with borg
  hosts: [ 'debops_service_borg_client' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.borg_client
      tags: [ 'role::borg_client' ]
